import nodemailer from 'nodemailer';
import { config } from '../../shared/config';
import { wrapHtml } from './email-template';

export interface EmailOptions {
  to: string | string[];
  subject: string;
  text?: string;
  html?: string;
  attachments?: { filename: string; content: Buffer; contentType?: string }[];
}

let _transporter: nodemailer.Transporter | null = null;

export function resetTransporter(): void {
  _transporter = null;
}

function getTransporter(): nodemailer.Transporter {
  if (!_transporter) {
    _transporter = nodemailer.createTransport({
      host: config.smtp.host,
      port: config.smtp.port,
      secure: config.smtp.port === 465,
      auth: {
        user: config.smtp.user,
        pass: config.smtp.pass,
      },
    });
  }
  return _transporter;
}

export async function sendEmail(options: EmailOptions): Promise<void> {
  const transporter = getTransporter();
  await transporter.sendMail({
    from: config.smtp.from,
    to: Array.isArray(options.to) ? options.to.join(', ') : options.to,
    subject: options.subject,
    text: options.text,
    html: options.html || (options.text ? wrapHtml(options.text.replace(/\n/g, '<br>'), options.subject) : undefined),
    attachments: options.attachments as any,
  });
}

export async function sendReportEmail(
  to: string[],
  reportName: string,
  format: string,
  fileBuffer: Buffer,
  fileName: string
): Promise<void> {
  const text = `Please find attached the scheduled report "${reportName}" in ${format.toUpperCase()} format.\n\nGenerated by Press Trust Scholarship Management System.`;
  await sendEmail({
    to,
    subject: `Scheduled Report: ${reportName}`,
    text,
    attachments: [{ filename: fileName, content: fileBuffer }],
  });
}
